# version: '3.9'

services:
  nextapp:
    container_name: nextapp
    image: nextapp
    build: .
    ports:
      - "3000:3000"
    environment:
    - AUTH_SECRET=FK775/kIFy8FjblxwkIZtIEXDgBhdU6BY48E4L1uceQ=
    env_file: 
      - path: .env
        required: true # default

