# version: '3.9'

services:
  nextapp:
    container_name: nextapp
    image: nextapp
    build: .
    ports:
      - "3000:3000"
    # environment:
    # - AUTH_SECRET=${AUTH_SECRET}
    env_file: 
      - path: .env.production
        required: true # default
  # demo:
  #   container_name: demo
  #   image: demo
  #   build: .
  #   ports:
  #     - "3001:3001"
  #   # environment:
  #   # - AUTH_SECRET=${AUTH_SECRET}
  #   env_file:
  #     - path: .env.production
  #       required: true # default

